# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/qcom/msm7x27a/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/qcom/msm7x27a/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/qcom/msm7x27a/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/qcom/msm7x27a/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/qcom/msm7x27a/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/qcom/msm7x27a/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/qcom/msm7x27a/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/qcom/msm7x27a/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/qcom/msm7x27a/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/qcom/msm7x27a/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/qcom/msm7x27a/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw
